import { RouteResult, RouteSegment, SelectedLocation, WeatherResponse } from './types';
import { getWeather } from './weather';
import { findCuratedLocation } from './indianLocations';

interface RouteCity { name: string; latitude: number; longitude: number; }

const KNOWN_ROUTES: Record<string, RouteCity[]> = {
  'delhi-chandigarh': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Sonipat', latitude: 28.9959, longitude: 77.0146 }, { name: 'Panipat', latitude: 29.3909, longitude: 76.9635 }, { name: 'Karnal', latitude: 29.6857, longitude: 76.9905 }, { name: 'Ambala', latitude: 30.3782, longitude: 76.7767 }, { name: 'Chandigarh', latitude: 30.7333, longitude: 76.7794 }],
  'delhi-jaipur': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Gurugram', latitude: 28.4595, longitude: 77.0266 }, { name: 'Manesar', latitude: 28.354, longitude: 76.936 }, { name: 'Bhiwadi', latitude: 28.21, longitude: 76.86 }, { name: 'Alwar', latitude: 27.566, longitude: 76.625 }, { name: 'Jaipur', latitude: 26.9124, longitude: 75.7873 }],
  'delhi-dehradun': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Meerut', latitude: 28.9845, longitude: 77.7064 }, { name: 'Muzaffarnagar', latitude: 29.4727, longitude: 77.7045 }, { name: 'Roorkee', latitude: 29.8543, longitude: 77.8883 }, { name: 'Haridwar', latitude: 29.9457, longitude: 78.1642 }, { name: 'Dehradun', latitude: 30.3165, longitude: 78.0322 }],
  'delhi-shimla': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Panipat', latitude: 29.3909, longitude: 76.9635 }, { name: 'Ambala', latitude: 30.3782, longitude: 76.7767 }, { name: 'Solan', latitude: 30.9045, longitude: 77.0967 }, { name: 'Shimla', latitude: 31.1048, longitude: 77.1734 }],
  'delhi-manali': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Panipat', latitude: 29.3909, longitude: 76.9635 }, { name: 'Ambala', latitude: 30.3782, longitude: 76.7767 }, { name: 'Chandigarh', latitude: 30.7333, longitude: 76.7794 }, { name: 'Mandi', latitude: 31.7099, longitude: 76.9328 }, { name: 'Manali', latitude: 32.2432, longitude: 77.1892 }],
  'mumbai-pune': [{ name: 'Mumbai', latitude: 19.076, longitude: 72.8777 }, { name: 'Navi Mumbai', latitude: 19.085, longitude: 73.0189 }, { name: 'Lonavala', latitude: 18.7546, longitude: 73.4062 }, { name: 'Pune', latitude: 18.5204, longitude: 73.8567 }],
  'bangalore-mysore': [{ name: 'Bangalore', latitude: 12.9716, longitude: 77.5946 }, { name: 'Ramanagara', latitude: 12.725, longitude: 77.282 }, { name: 'Mandya', latitude: 12.523, longitude: 76.896 }, { name: 'Mysore', latitude: 12.2958, longitude: 76.6394 }],
  'chennai-bangalore': [{ name: 'Chennai', latitude: 13.0827, longitude: 80.2707 }, { name: 'Kanchipuram', latitude: 12.8342, longitude: 79.7141 }, { name: 'Vellore', latitude: 12.9165, longitude: 79.1325 }, { name: 'Krishnagiri', latitude: 12.526, longitude: 78.215 }, { name: 'Bangalore', latitude: 12.9716, longitude: 77.5946 }],
  'kolkata-gangtok': [{ name: 'Kolkata', latitude: 22.5726, longitude: 88.3639 }, { name: 'Siliguri', latitude: 26.7271, longitude: 88.3953 }, { name: 'Gangtok', latitude: 27.3389, longitude: 88.6065 }],
  'delhi-gangtok': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Lucknow', latitude: 26.8467, longitude: 80.9462 }, { name: 'Patna', latitude: 25.5941, longitude: 85.1376 }, { name: 'Siliguri', latitude: 26.7271, longitude: 88.3953 }, { name: 'Gangtok', latitude: 27.3389, longitude: 88.6065 }],
  'delhi-rishikesh': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Meerut', latitude: 28.9845, longitude: 77.7064 }, { name: 'Haridwar', latitude: 29.9457, longitude: 78.1642 }, { name: 'Rishikesh', latitude: 30.0869, longitude: 78.2676 }],
  'delhi-nainital': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Moradabad', latitude: 28.8386, longitude: 78.7733 }, { name: 'Rampur', latitude: 28.817, longitude: 79.029 }, { name: 'Haldwani', latitude: 29.2183, longitude: 79.5286 }, { name: 'Nainital', latitude: 29.3919, longitude: 79.4542 }],
};

function normalizeCity(name: string): string { return name.toLowerCase().trim().replace(/\s+/g, ''); }
function getRouteKey(start: string, end: string): string { const s = normalizeCity(start); const e = normalizeCity(end); if (KNOWN_ROUTES[`${s}-${e}`]) return `${s}-${e}`; if (KNOWN_ROUTES[`${e}-${s}`]) return `${e}-${s}`; const sAliases: Record<string, string> = { delhi: 'delhi', newdelhi: 'delhi', bengaluru: 'bangalore', bombay: 'mumbai', madras: 'chennai' }; const eAliases: Record<string, string> = { delhi: 'delhi', newdelhi: 'delhi', bengaluru: 'bangalore', bombay: 'mumbai', madras: 'chennai' }; const sn = sAliases[s] || s; const en = eAliases[e] || e; if (KNOWN_ROUTES[`${sn}-${en}`]) return `${sn}-${en}`; if (KNOWN_ROUTES[`${en}-${sn}`]) return `${en}-${sn}`; return ''; }
function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number { const R = 6371; const dLat = ((lat2 - lat1) * Math.PI) / 180; const dLon = ((lon2 - lon1) * Math.PI) / 180; const a = Math.sin(dLat / 2) ** 2 + Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) ** 2; return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))); }
function assessRainRisk(prob: number, precip: number): 'low' | 'medium' | 'high' { if (prob >= 60 || precip >= 10) return 'high'; if (prob >= 30 || precip >= 2) return 'medium'; return 'low'; }
function assessVisibility(vis: number): 'good' | 'moderate' | 'poor' { if (vis > 0 && vis < 1000) return 'poor'; if (vis > 0 && vis < 5000) return 'moderate'; return 'good'; }
function assessWind(wind: number): 'calm' | 'moderate' | 'strong' { if (wind >= 35) return 'strong'; if (wind >= 20) return 'moderate'; return 'calm'; }
function assessHazard(rain: 'low' | 'medium' | 'high', vis: 'good' | 'moderate' | 'poor', wind: 'calm' | 'moderate' | 'strong', code: number): 'safe' | 'caution' | 'dangerous' { if (rain === 'high' || vis === 'poor' || wind === 'strong' || code >= 95) return 'dangerous'; if (rain === 'medium' || vis === 'moderate' || wind === 'moderate') return 'caution'; return 'safe'; }

async function buildRouteFromCities(cities: RouteCity[], isReversed: boolean): Promise<RouteResult> {
  const orderedCities = isReversed ? [...cities].reverse() : cities;
  const weatherResults = await Promise.all(orderedCities.map(async (c) => { const w = await getWeather(c.latitude, c.longitude, c.name); return { city: c, weather: w }; }));
  const segments: RouteSegment[] = weatherResults.map(({ city, weather }) => { const c = weather.current; const today = weather.daily[0]; const rainRisk = assessRainRisk(today?.precipitationProbability || c.precipitation, today?.precipitationSum || c.precipitation); const visStatus = assessVisibility(c.visibility); const windStatus = assessWind(c.windSpeed); const hazardLevel = assessHazard(rainRisk, visStatus, windStatus, c.weatherCode); return { name: city.name, latitude: city.latitude, longitude: city.longitude, weather, rainRisk, visibilityStatus: visStatus, windStatus, hazardLevel, conditionSummary: `${c.description}, ${c.temperature}°C, ${today?.precipitationProbability || 0}% rain, ${c.windSpeed} km/h wind` }; });
  let totalDistance = 0; for (let i = 0; i < orderedCities.length - 1; i++) totalDistance += calculateDistance(orderedCities[i].latitude, orderedCities[i].longitude, orderedCities[i + 1].latitude, orderedCities[i + 1].longitude);
  const hazardScores = segments.map((s) => { let score = 0; if (s.hazardLevel === 'dangerous') score += 40; else if (s.hazardLevel === 'caution') score += 20; if (s.rainRisk === 'high') score += 20; else if (s.rainRisk === 'medium') score += 10; if (s.visibilityStatus === 'poor') score += 15; else if (s.visibilityStatus === 'moderate') score += 8; if (s.windStatus === 'strong') score += 15; else if (s.windStatus === 'moderate') score += 7; return score; });
  const avgHazardScore = hazardScores.reduce((a, b) => a + b, 0) / hazardScores.length; const weatherRiskScore = Math.min(100, Math.round(avgHazardScore));
  let status = 'RECOMMENDED'; if (weatherRiskScore >= 50) status = 'CAUTION'; else if (weatherRiskScore >= 70) status = 'HIGH RISK';
  const etaHours = Math.max(1, Math.round((totalDistance / 60) * 10) / 10); const etaStr = `${Math.floor(etaHours)}h ${Math.round((etaHours - Math.floor(etaHours)) * 60)}m`;
  return { routeLabel: 'A', segments, totalDistance, weatherRiskScore, eta: etaStr, status, recommendation: '', isRecommended: false };
}

export async function analyzeRoute(startName: string, endName: string): Promise<{ routes: RouteResult[]; startLocation: SelectedLocation | null; endLocation: SelectedLocation | null }> {
  const routeKey = getRouteKey(startName, endName); const isReversed = routeKey ? KNOWN_ROUTES[routeKey]?.[0]?.name.toLowerCase() !== normalizeCity(startName) : false;
  const startCurated = findCuratedLocation(startName); const endCurated = findCuratedLocation(endName);
  const startLocation: SelectedLocation | null = startCurated ? { city: startCurated.city, state: startCurated.state, country: startCurated.country, latitude: startCurated.latitude, longitude: startCurated.longitude, timezone: startCurated.timezone } : null;
  const endLocation: SelectedLocation | null = endCurated ? { city: endCurated.city, state: endCurated.state, country: endCurated.country, latitude: endCurated.latitude, longitude: endCurated.longitude, timezone: endCurated.timezone } : null;
  if (routeKey) { const cities = KNOWN_ROUTES[routeKey]; const routeA = await buildRouteFromCities(cities, isReversed); const altKey = `${routeKey}_alt`; let routeB: RouteResult | null = null; const alternatives: Record<string, RouteCity[]> = { 'delhi-chandigarh_alt': [{ name: 'Delhi', latitude: 28.6139, longitude: 77.209 }, { name: 'Rohtak', latitude: 28.8955, longitude: 76.6066 }, { name: 'Jind', latitude: 29.314, longitude: 76.309 }, { name: 'Kaithal', latitude: 29.797, longitude: 76.398 }, { name: 'Pehowa', latitude: 29.979, longitude: 76.586 }, { name: 'Chandigarh', latitude: 30.7333, longitude: 76.7794 }] };
  if (alternatives[altKey]) { routeB = await buildRouteFromCities(alternatives[altKey], false); routeB.routeLabel = 'B'; }
  const routes = [routeA]; if (routeB) routes.push(routeB);
  if (routes.length === 1) { routes[0].isRecommended = true; routes[0].recommendation = 'This is the only known route. Check weather conditions along the way.'; } else { const recommended = routes.reduce((best, r) => (r.weatherRiskScore < best.weatherRiskScore ? r : best)); recommended.isRecommended = true; const other = routes.find((r) => !r.isRecommended)!; recommended.recommendation = `Route ${recommended.routeLabel} has lower weather risk (${recommended.weatherRiskScore}/100 vs ${other.weatherRiskScore}/100). ${recommended.totalDistance > other.totalDistance ? 'It is slightly longer but safer.' : 'It is also shorter.'}`; other.recommendation = `Route ${other.routeLabel} has higher weather risk. Consider Route ${recommended.routeLabel} instead.`; }
  return { routes, startLocation, endLocation }; }
  if (!startLocation || !endLocation) return { routes: [], startLocation, endLocation };
  const startWeather = await getWeather(startLocation.latitude, startLocation.longitude, startLocation.city); const endWeather = await getWeather(endLocation.latitude, endLocation.longitude, endLocation.city);
  const startSeg: RouteSegment = { name: startLocation.city, latitude: startLocation.latitude, longitude: startLocation.longitude, weather: startWeather, rainRisk: assessRainRisk(startWeather.daily[0]?.precipitationProbability || 0, startWeather.daily[0]?.precipitationSum || 0), visibilityStatus: assessVisibility(startWeather.current.visibility), windStatus: assessWind(startWeather.current.windSpeed), hazardLevel: 'caution', conditionSummary: `${startWeather.current.description}, ${startWeather.current.temperature}°C` };
  const endSeg: RouteSegment = { name: endLocation.city, latitude: endLocation.latitude, longitude: endLocation.longitude, weather: endWeather, rainRisk: assessRainRisk(endWeather.daily[0]?.precipitationProbability || 0, endWeather.daily[0]?.precipitationSum || 0), visibilityStatus: assessVisibility(endWeather.current.visibility), windStatus: assessWind(endWeather.current.windSpeed), hazardLevel: 'caution', conditionSummary: `${endWeather.current.description}, ${endWeather.current.temperature}°C` };
  const dist = calculateDistance(startLocation.latitude, startLocation.longitude, endLocation.latitude, endLocation.longitude); const riskScore = Math.round((startSeg.rainRisk === 'high' ? 40 : startSeg.rainRisk === 'medium' ? 20 : 5) + (endSeg.rainRisk === 'high' ? 40 : endSeg.rainRisk === 'medium' ? 20 : 5)) / 2;
  const route: RouteResult = { routeLabel: 'A', segments: [startSeg, endSeg], totalDistance: dist, weatherRiskScore: Math.min(100, riskScore), eta: `${Math.max(1, Math.round(dist / 60))}h 0m`, status: riskScore >= 50 ? 'CAUTION' : 'RECOMMENDED', recommendation: 'Route shown with start and end points. Intermediate weather data is available for major Indian routes only. This does not replace official navigation services.', isRecommended: true };
  return { routes: [route], startLocation, endLocation };
}

export function formatRouteResult(routes: RouteResult[]): string {
  if (routes.length === 0) return 'Could not analyze this route. Please check the city names.';
  let text = '';
  for (const route of routes) { text += `Route ${route.routeLabel}:\nDistance: ${route.totalDistance} km\nWeather Risk: ${route.weatherRiskScore}/100\nETA: ${route.eta}\nStatus: ${route.status}\nSegments:\n`; for (const seg of route.segments) text += `  ${seg.name}: ${seg.conditionSummary} | Rain: ${seg.rainRisk} | Visibility: ${seg.visibilityStatus} | Wind: ${seg.windStatus} | Hazard: ${seg.hazardLevel}\n`; text += `${route.recommendation}\n\n`; }
  text += 'Note: WeatherGPT does not replace official navigation services. Use Google Maps or similar for turn-by-turn directions.';
  return text;
}
